// <auto-generated />
using System;
using HumanResourceApp.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanResourceApp.Migrations
{
    [DbContext(typeof(RepositoryBase))]
    partial class RepositoryBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanResourceApp.Model.DogadjajiModel", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("smallint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2")
                        .HasColumnName("Datum");

                    b.Property<string>("TekstDogadjaja")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar")
                        .HasColumnName("Ime");

                    b.Property<short>("ZaposleniciId")
                        .HasMaxLength(3)
                        .HasColumnType("smallint")
                        .HasColumnName("ZaposleniciId");

                    b.HasKey("Id");

                    b.HasIndex("ZaposleniciId");

                    b.ToTable("Dogadjaji");
                });

            modelBuilder.Entity("HumanResourceApp.Model.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HumanResourceApp.Model.ZaposleniciModel", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("smallint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar")
                        .HasColumnName("Adresa");

                    b.Property<DateTime>("DatumDodavanja")
                        .HasColumnType("datetime2")
                        .HasColumnName("DatumDodavanja");

                    b.Property<DateTime>("DatumIzmjene")
                        .HasColumnType("datetime2")
                        .HasColumnName("DatumIzmjene");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Grad");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("Ime");

                    b.Property<byte>("Pol")
                        .HasColumnType("tinyint")
                        .HasColumnName("Pol");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("Prezime");

                    b.HasKey("Id");

                    b.ToTable("Zaposlenici");
                });

            modelBuilder.Entity("HumanResourceApp.Model.DogadjajiModel", b =>
                {
                    b.HasOne("HumanResourceApp.Model.ZaposleniciModel", "Zaposlenici")
                        .WithMany("Dogadjaji")
                        .HasForeignKey("ZaposleniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zaposlenici");
                });

            modelBuilder.Entity("HumanResourceApp.Model.ZaposleniciModel", b =>
                {
                    b.Navigation("Dogadjaji");
                });
#pragma warning restore 612, 618
        }
    }
}
